services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD", "og_isready", "-U", "postgres", "-d", "postgres"]
#      interval: 10s
#      retries: 5
#      start_period: 30w
#      timeout: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      - DEBUG=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    command: bash -c 'fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./src:/usr/src/src



