services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "og_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: bash -c 'alembic upgrade head && fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./src:/usr/src/src

networks:
  app-network:
    driver: bridge